name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7
    - uses: actions/checkout@v2
    - name: Update Conda environment with "environment.yml"
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./environment.yml
    - name: pytest
      run: |
        pip install pytest
        pip install pytest-cov
        python -m pytest --cov=hyperspec --cov-report=xml --cov-report=html
